const express=require("express");
const app=express();
const env=require('dotenv');
env.config();
const path=require('path');
app.set('view engine','ejs');
app.set('views',path.join(__dirname,'views'));
app.use(express.urlencoded({extended:true}));
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());
const db=require('./db/user');
db();
const user=require('./routs/user.routes');
app.use('/',user);
const blog=require('./routs/blog.routes');
app.use('/',blog);
const showblog=require('./routs/show_blog.routes');
app.use('/',showblog);
module.exports=app;